plugins {
    id 'fabric-loom' version '1.6.12'
    id 'maven-publish'
}

repositories {
    // дублировать не обязательно (есть в settings), но так нагляднее
    maven { url 'https://libraries.minecraft.net/' }
    maven { url 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    // версия игры
    minecraft "com.mojang:minecraft:1.20.1"

    // маппинги Yarn (в Loom 1.6 нельзя использовать loom.yarn(...))
    mappings "net.fabricmc:yarn:1.20.1+build.10:v2"

    // загрузчик Fabric
    modImplementation "net.fabricmc:fabric-loader:0.14.22"

    // ТОЛЬКО монолитный Fabric API (никаких подмодулей!)
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.3+1.20.1"
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

// опционально: публикация — можно не трогать
publishing {
    publications { }
    repositories { }
}
