pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        // Mojang libraries (authlib и пр.)
        maven { url 'https://libraries.minecraft.net/' }
        // Основные
        maven { url 'https://maven.fabricmc.net/' }
        mavenCentral()
        gradlePluginPortal()
        // Резервное зеркало (на случай сетевых глюков)
        maven { url 'https://maven.minecraftforge.net/' }
    }
}

rootProject.name = 'neorifts'
